version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./main.js:/usr/share/nginx/html/main.js
      - ./media/.:/usr/share/nginx/html/media/.
    ports:
      - "80:80"